name: Setup & Install Dependencies
description: Sets Node.js up and installs project dependencies

inputs:
  repository:
    description: Repository path.
    required: true
  token:
    description: Personal access token (PAT) used to create the PR.
    required: true

runs:
  using: composite
  steps:
    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v5
      with:
        path: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        commit-message: |
          [auto-sync] update task list

          Updated from ${{ github.repository }}@${{ github.sha }}
        title: "🤖[auto-sync] update task list"
        body: |
          ## Automated Task List Update

          **Source:** ${{ github.repository }}@${{ github.sha }}

          Please review and merge when ready.

          ---
          _Created automatically by GitHub Actions_
        branch: task-list/auto-sync
        delete-branch: true
        author: "[osrs-taskbot] <r.mobis+taskbot@gmail.com>"
        committer: "[osrs-taskbot] <r.mobis+taskbot@gmail.com>"

    - name: Create summary
      shell: bash
      run: |
        if [ "${{ steps.create-pr.outputs.pull-request-number }}" != "" ]; then
          echo "## ✅ Pull Request ${{ steps.create-pr.outputs.pull-request-operation }}" >> $GITHUB_STEP_SUMMARY
          echo "- **PR Link**: ${{ steps.create-pr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
          echo "_Please review and merge the PR in the target repository_" >> $GITHUB_STEP_SUMMARY
        else
          echo "## ℹ️ No changes detected" >> $GITHUB_STEP_SUMMARY
        fi
