name: Fix & Lint

on:
  pull_request_target:
    branches: ["main"]

jobs:
  check-prereqs:
    name: Check for Prerequisites
    runs-on: ubuntu-slim

    outputs:
      require_approval: ${{ steps.check-sensitive.outputs.any_changed || false }}
      skip_fix: ${{ contains(steps.skip-fix.outputs.commit_message, 'skip-fix') }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 2
          allow-unsafe-pr-checkout: true

      - name: Check Changed Sensitive Files
        id: check-sensitive
        if: github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
        uses: tj-actions/changed-files@v47
        with:
          files: |
            .github/**
            package*.json
            **.mts
            lefthook.yml

      - name: Get Latest Commit Message
        id: skip-fix
        run: |
          echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
          git log -1 --pretty=%B ${{ github.event.pull_request.head.sha }} >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  request-approval:
    name: Request Approval
    runs-on: ubuntu-slim
    environment: Require Approval
    needs: check-prereqs
    if: needs.check-prereqs.outputs.require_approval != 'false'

    steps:
      - run: true

  safety-gate:
    name: Safety Gate
    runs-on: ubuntu-slim
    needs: [check-prereqs, request-approval]
    if: |
      always() &&
      needs.check-prereqs.result == 'success' &&
      (needs.request-approval.result == 'success' || needs.check-prereqs.outputs.require_approval == 'false')

    steps:
      - run: true

  fix:
    name: Fix
    runs-on: ubuntu-slim
    needs: [safety-gate, check-prereqs]
    if: |
      always() &&
      needs.safety-gate.result == 'success' &&
      needs.check-prereqs.result == 'success' &&
      needs.check-prereqs.outputs.skip_fix != 'true'

    outputs:
      skip_lint: ${{ steps.commit-changes.outputs.changes_detected }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.ROBOT_GITHUB_TOKEN }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          allow-unsafe-pr-checkout: true
      - uses: ./.github/actions/setup

      - name: Format Code
        shell: bash
        run: npm run format

      - name: Generate UUIDs
        shell: bash
        run: npm run gen:uuids

      - name: Commit Changes
        id: commit-changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_author: "${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.login }}+${{ github.event.pull_request.user.id }}@users.noreply.github.com>"
          commit_user_name: osrs-taskbot
          commit_user_email: r.mobis+taskbot@gmail.com
          commit_message: "[skip-fix] format and generate missing UUIDs"

  lint-gate:
    name: Lint Gate
    runs-on: ubuntu-slim
    needs: [safety-gate, fix]
    if: |
      always() &&
      needs.safety-gate.result == 'success' &&
      needs.fix.outputs.skip_lint != 'true'

    steps:
      - run: true

  lint:
    name: General Linting
    needs: lint-gate
    if: |
      always() &&
      needs.lint-gate.result == 'success'
    runs-on: ubuntu-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: ./.github/actions/setup

      - name: Lint code
        run: npm run lint:ultracite

      - name: Lint tasks
        run: npm run lint:tasks

      - name: Lint schema
        run: npm run lint:schema

      - name: Lint UUIDs
        run: npm run lint:uuids

  lint-links:
    name: Link Links
    needs: lint-gate
    if: |
      always() &&
      needs.lint-gate.result == 'success'
    runs-on: ubuntu-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: ./.github/actions/setup

      - name: Cache
        uses: actions/cache@v6
        with:
          path: .cache
          key: cache-${{ hashFiles('tiers/*.json') }}
          restore-keys: |
            cache-

      - name: Lint links
        run: npm run lint:links

  check-types:
    name: Check Typescript Types
    needs: lint-gate
    if: |
      always() &&
      needs.lint-gate.result == 'success'
    runs-on: ubuntu-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: ./.github/actions/setup

      - name: Generate types
        run: npm run gen:types

      - name: Ensure types are up to date
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi
