name: Lint & Check Generation

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Lint code
        run: npm run lint

  check-types:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Generate types
        run: npm run gen:types

      - name: Ensure types are up to date
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi
