name: Synchronize Clog Master Plugin Task List

on:
  push:
    branches: ["main"]
    paths: ["tiers/*.json", ".github/workflows/sync-clogmaster-task-list.yml"]
  workflow_dispatch:

jobs:
  sync-tedious-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Generate list
        run: npm run gen:list:tedious

      - name: Checkout plugin repository
        uses: actions/checkout@v4
        with:
          repository: OSRS-Taskman/collection-log-master
          token: ${{ secrets.ROBOT_GITHUB_TOKEN }}
          path: collection-log-master

      - name: Copy task list to plugin repository
        run: |
          cp lists/tedious.json collection-log-master/src/main/resources/com/collectionlogmaster/task-list.json
          cp lists/tedious.json collection-log-master/src/main/resources/com/collectionlogmaster/domain/task-list.json
          cp lists/tedious.json collection-log-master/src/main/resources/com/logmaster/domain/task-list.json

      - name: Create PR
        uses: ./.github/actions/create-pr
        with:
          target-repo: collection-log-master
