name: Sync Tedious Task List

on:
  push:
    branches: ["main"]
    paths: ["lists/tedious.json"]
  workflow_dispatch:
    inputs:
      target_repo:
        description: "Target repository (owner/repo)"
        required: true
        default: "RedSparr0w/runelite-generate-task"
      target_path:
        description: "Target file path in destination repo"
        required: true
        default: "src/main/resources/com/logmaster/domain/tedious.json"

jobs:
  sync-tedious-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set target repository
        id: set-target
        run: |
          echo "target_repo=${{ github.event.inputs.target_repo }}" >> $GITHUB_OUTPUT
          echo "target_path=${{ github.event.inputs.target_path }}" >> $GITHUB_OUTPUT

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.set-target.outputs.target_repo }}
          token: ${{ secrets.SYNC_TOKEN }}
          path: target-repo

      - name: Copy tedious.json to target repository
        run: |
          mkdir -p target-repo/$(dirname "${{ steps.set-target.outputs.target_path }}")
          cp lists/tedious.json "target-repo/${{ steps.set-target.outputs.target_path }}"

      - name: Check for changes in target repository
        id: verify-changed-files
        working-directory: target-repo
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Files changed:"
            git status --porcelain
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Commit and push to target repository
        if: steps.verify-changed-files.outputs.changed == 'true'
        working-directory: target-repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Sync"
          git add "${{ steps.set-target.outputs.target_path }}"
          git commit -m "Auto-sync: Update tedious task list"
          git push

      - name: Create summary
        run: |
          echo "## Sync Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Source file**: \`lists/tedious.json\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Target repository**: \`${{ steps.set-target.outputs.target_repo }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Target path**: \`${{ steps.set-target.outputs.target_path }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Changes detected**: \`${{ steps.verify-changed-files.outputs.changed }}\`" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
            echo "- **Status**: ✅ Successfully synced" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Status**: ℹ️ No changes needed" >> $GITHUB_STEP_SUMMARY
          fi
